2024-07-25 12:06:00,766 ERROR scheduler Exception in Enqueue Events for Site mysite.localhost
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_c37b8de16a526fec'@'localhost' (using password: YES)")
2024-07-29 20:22:00,733 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 20:26:00,864 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 20:30:01,084 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 20:34:00,364 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 20:38:00,550 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 20:42:00,656 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 20:46:00,989 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 20:50:01,190 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 20:54:00,297 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 20:58:00,518 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:02:00,719 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:06:00,879 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:10:01,067 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:14:00,249 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:18:00,544 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:22:00,734 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:26:00,814 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:30:01,009 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:34:00,290 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:38:00,489 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:42:00,592 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:46:00,797 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:50:00,892 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:54:01,125 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 21:58:00,310 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 22:02:00,416 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-29 22:06:00,631 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 10:06:00,545 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 10:10:00,827 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 10:14:00,940 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 10:18:02,994 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 10:22:01,111 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
