2024-07-30 16:46:01,119 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 16:50:00,333 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 16:54:00,550 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 16:58:00,584 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:02:00,839 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:06:00,944 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:10:00,133 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:14:00,428 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:18:00,638 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:22:00,853 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:26:00,945 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:30:00,148 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:34:00,354 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:38:00,560 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:42:00,769 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:46:00,996 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:50:00,226 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:54:00,458 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 17:58:00,707 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 18:02:00,922 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 18:06:00,128 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 18:10:00,599 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 18:22:00,214 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 20:18:00,903 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 20:22:00,249 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 20:26:00,437 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 20:30:00,623 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 20:34:00,827 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 20:38:01,005 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 20:42:00,084 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 20:46:00,330 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 20:50:00,536 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
2024-07-30 20:54:00,732 ERROR scheduler Exception in Enqueue Events for Site irfancabs
Traceback (most recent call last):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/priya/Desktop/frappe-training/my-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/priya/Desktop/frappe-training/my-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_4a24312bc35d674b'@'localhost' (using password: YES)")
