Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1164, in run
Traceback (most recent call last):
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1026, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 837, in parse_response
    response = self._execute(conn, try_read)
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 813, in _execute
    return conn.retry.call_with_retry(
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 512, in read_response
    fail(error)
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 815, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 802, in _disconnect_raise_connect
    raise error
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 814, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 831, in try_read
    if not conn.can_read(timeout=timeout):
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 490, in can_read
    return self._parser.can_read(timeout)
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/_parsers/hiredis.py", line 75, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/_parsers/hiredis.py", line 86, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/_parsers/hiredis.py", line 124, in read_response
    self.read_from_socket()
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/_parsers/hiredis.py", line 84, in read_from_socket
    bufflen = self._sock.recv_into(self._buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/priya/Desktop/frappe-training/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 128, in <module>
    main()
  File "/home/priya/Desktop/frappe-training/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 34, in main
    FrappeCommandGroup(commands=commands)(prog_name="bench")
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/priya/Desktop/frappe-training/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 205, in start_worker
    start_worker(
  File "/home/priya/Desktop/frappe-training/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 314, in start_worker
    worker.work(
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 458, in work
    self.teardown()
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1048, in teardown
    self.register_death()
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 834, in register_death
    p.execute()
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/client.py", line 1494, in execute
    conn = self.connection_pool.get_connection("MULTI", self.shard_hint)
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 1109, in get_connection
    connection.connect()
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 288, in connect
    self.on_connect()
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 391, in on_connect
    self.read_response()
  File "/home/priya/Desktop/frappe-training/frappe-bench/env/lib/python3.10/site-packages/redis/connection.py", line 520, in read_response
    raise ConnectionError(
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:11001 : (104, 'Connection reset by peer')
